config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'static/home'
  root 'static#home'
  
  
  get         'users/new'
  get         'signup'  => 'users#new'
  get         'sessions/new'
  get         'login'   => 'sessions#new'
  post        'login'   => 'sessions#create'
  delete      'logout'  => 'sessions#destroy'
  resources   :users
  
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :order, only: [:create, :update, :show, :destroy]
  
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'confirm_checkout' => "order#update"

  get 'store'     => 'products#index'
  get 'checkout'  => 'order#show'
  get 'carts/show'
  get 'empty_cart' => 'order#destroy'
  
   get 'stats'   => 'static#stats'
  
  
  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_one :user
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal
  
  def subtotal
      order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
  private
    def set_order_status
      self.order_status = 1
    end

    def update_subtotal
        self[:subtotal] = subtotal
    end
  
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
  end
  
  def show
    #Only allow logged in users to checkout
    redirect_to login_url if !logged_in?
    @order = current_order
    @items = current_order.order_items
    @user = current_user
  end
  
  # THIS IS WHERE ORDERS ARE FAKE COMPLETED
  # BY HAVING THE STATUS CHANGEDAND SESSION CLEARED
  def update
    order = current_order
    order.update_attributes( order_status: 2 )
    order.save
    @order = order
    session[:order_id] = nil
    
    # TRIGGER PUSHER 
    @message = params[:message]
    Pusher['updates_channel'].trigger('app_update', { 
      order: order, 
      products: order.order_items, 
      user: current_user 
    })
    
  end

  # Empty the cart by destroying the order
  def destroy
    order = current_order
    
    # Need to destroy dependant order items first
    OrderItem.where(order_id: order.id).destroy_all
    
    # Optionally destroy order and start new session
    # to prevent accumulation of empty orders
    order.destroy
    
    # Start new session
    session[:order_id] = nil
    
    redirect_to store_url
  end
end

app/views/order/_cart_contents.html.erb
<% if !@item.nil? && @item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @items.each do |order_item| %>
    <%= render 'cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/order/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.title %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="quantity text-right">Quantity: <%= order_item.quantity.to_i %></div>
    
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/order/_customer_details.html.erb
<div class="checkout text-center">
    <h3><b>Total:</b> <%= number_to_currency current_order.subtotal %></h3>
    <br />
    <br />
    <h3><b>Confirm your details</b></h2>
    
    <div>
        <b>Name:</b> 
        <%= @user.first %>, <%= @user.last %> 
    </div>
    
    <div>
        <b>Country:</b> 
        <%= @user.country %>
    </div>
    
    <div>
        <b>City:</b> 
        <%= @user.city %>
    </div>
    
    <br />
    <br />
    
</div>

app/views/order/show.html.erb
<h1 class="text-center">CHECKOUT</h1>
<%= render "cart_contents" %>
<%= render "customer_details" %>
<div class="text-center mb-25">
    <%= link_to "Confirm Checkout", order_path(@order), method: "put", id:"checkout-btn",  class: "btn btn-default"  %>
</div>

app/views/order/update.html.erb
<div class="text-center">
    <h1>SUCCESS!</h1>
    Your order is on its way to beautiful <%= current_user.city %>
</div>
<div id="congrats">
    <%= image_tag "congrats.jpg", alt: "CONGRATS!" %>
</div>