config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'static/home'
  root 'static#home'
  
  
  get         'users/new'
  get         'signup'  => 'users#new'
  get         'sessions/new'
  get         'login'   => 'sessions#new'
  post        'login'   => 'sessions#create'
  delete      'logout'  => 'sessions#destroy'
  resources   :users
  
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :order, only: [:create, :update, :show, :destroy]
  
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'confirm_checkout' => "order#update"

  get 'store'     => 'products#index'
  get 'checkout'  => 'order#show'
  get 'carts/show'
  get 'empty_cart' => 'order#destroy'
  
   get 'stats'   => 'static#stats'
  
  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
    has_attached_file :image, :styles => {  
        :medium => "400x400", 
        :thumb => "100x100" 
    }, :default_url => "missing.jpg", width:200
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.paginate(page: params[:page], :per_page => 6)
    @order_item = current_order.order_items.new
  end

  # GET /products/1
  def show
    @order_item = current_order.order_items.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :image, :price, :active)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<div class="col-xs-12 col-md-6 product">
      
    <a class="product-info" href="/products/<%=product.id%>">
      
        <%= image_tag product.image.url(:medium), width:150 %>
        <h3 class="text-uppercase"><%= product.title %></h3>
    </a>
    <%= product.description %>
      
    
    <div class="">
      
      <%= form_for order_item do |f| %>
      <h4 class=""><span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
      <% #if current_user.admin? %>
        <small><%= link_to 'Edit', edit_product_path(product) %></small>
      <% #end %>
    </div>
</div>

app/views/products/edit.html.erb
<% provide(:title, 'Create Product') %>
<h1 class="text-center">Create a product</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @product, html: { multipart: true } do |f| %>
        
        <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title %>
        </div>

        <div class="field">
            <%= f.label :description %><br>
            <%= f.text_area :description %>
        </div>
        
        <div class="field">
            <%= f.label :price %><br>
            <%= f.text_field :price %>
        </div>
        
        <div class="field">
            <%= f.file_field :image %>
        </div>

      <%= f.submit "Create Beverage!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<h1 class="text-center">The Fizz, the Buzz, the beverages:</h1>

<div class="row">
  <div class="col-xs-12">
    <%= will_paginate %>
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
    <%= will_paginate %>
  </div>
</div>

app/views/products/new.html.erb
<% provide(:title, 'Create Product') %>
<h1>Create a product</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @product, html: { multipart: true } do |f| %>
        
        <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title %>
        </div>
        
        <div class="field">
            <%= f.label :price %><br>
            <%= f.text_field :price %>
        </div>

        <div class="field">
            <%= f.label :description %><br>
            <%= f.text_area :description %>
        </div>
        
        <div class="field">
            <%= f.file_field :image %>
        </div>

      <%= f.submit "Create Beverage!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="text-center mb-25 p-25 product">
    <%= image_tag @product.image.url(:medium), width:400 %>
    <h1 class="text-center"><%= @product.title %></h1>
    <div class="input-group">
        <%= @product.description %>
        <%= form_for @order_item do |f| %>
            <h4 class=""><span><%= number_to_currency @product.price %></span></h4>
            <div class="input-group">
              <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
              <div class="input-group-btn">
                <%= f.hidden_field :product_id, value: @product.id %>
                <%= f.submit "Add to Cart", class: "btn btn-primary" %>
              </div>
            </div>
        <% end %>
    </div>
    <% #if current_user.admin? %>
    <small><%= link_to 'Edit', edit_product_path(@product) %></small>
    <% #end %>
</div>