config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'static/home'
  root 'static#home'
  
  
  get         'users/new'
  get         'signup'  => 'users#new'
  get         'sessions/new'
  get         'login'   => 'sessions#new'
  post        'login'   => 'sessions#create'
  delete      'logout'  => 'sessions#destroy'
  resources   :users
  
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :order, only: [:create, :update, :show, :destroy]
  
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'confirm_checkout' => "order#update"

  get 'store'     => 'products#index'
  get 'checkout'  => 'order#show'
  get 'carts/show'
  get 'empty_cart' => 'order#destroy'
  
   get 'stats'   => 'static#stats'
  
  
  

end

app/views/layouts/_footer.html.erb
</main>
<footer class="footer">
  <div class="container">
    <h2 class="text-center"><%= title %></h2>
    <nav class="navbar text-center">
      <ul class="navbar-nav nav">
        <li><%= link_to "home",   root_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>

        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <% if has_cart %>
          
            <li><%= link_to "Checkout #{current_order.order_items.size}", checkout_path  %></li>
            <li><%= link_to "Empty Cart", empty_cart_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Customer Service</a></li>
        <li><a href="#">Privacy</a></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="top-header" class="navbar navbar-inverse navbar-collapse">
  <div class="container">
    
    <a href="/" id="logo">
      <h1>
        <%= image_tag "fb-logo.png", alt: "#{title}", width:"80px" %><br/>
        <%= title %>
      </h1>
    </a>
      
    
    
    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#top-nav" aria-controls="bs-navbar" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <nav id="top-nav" class="collapse navbar-collapse text-center">
      <ul class="nav navbar-nav ">
        <li><%= link_to "Shop!", store_path %></li>
        <li><%= link_to "Sales Stats", stats_path %></li>
      
      <% if logged_in? %>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" 
          role="button" aria-haspopup="true" 
          aria-expanded="false">
            Account <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
      <% if has_cart %>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" 
          role="button" aria-haspopup="true" 
          aria-expanded="false">
            Cart (<%= current_order.order_items.size %>) <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "View/Edit Cart", cart_path  %></li>
            <li><%= link_to "Checkout", checkout_path  %></li>
            <li><%= link_to "Empty Cart", empty_cart_path %></li>
          </ul>
        </li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>
<main id="content">

app/views/layouts/_pusher_app.js.erb
<style>
.hidden{ opacity: 0; height: 0; padding:0; transition: all .2s ease; }
.order{ transition: all .2s ease; padding: 20px 0; border-bottom: 1px dashed #aaa; }
</style>
<script>
// Enable pusher logging - don't include this in production

"user strict";

Pusher.log = function(message) {
  if (window.console && window.console.log) {
    window.console.log(message);
  }
};

var pusher = new Pusher('9a3be651fc6e022d4c10', {
  encrypted: true
});

var channel = pusher.subscribe('updates_channel');

channel.bind('app_update', function(data) {
    var 
    name = data.user.first,
    total = data.order.subtotal,
    country = data.user.country,
    city = data.user.city, 
    quantity = 0,
    products = data.products,
    tmp;

    for(var i=0; i<products.length; i++)
        quantity += products[i].quantity
    
    var rr = '<div class="order hidden"><h3>$'+total+ ' - ' +city+'<br/><small>'+ data.order.updated_at +'</small></h3><div class="order-name"><b>Name:</b> '+ name +'</div><div class="order-country"><b>country:</b> '+ country +'</div><div class="order-city"><b>city:</b> '+ city +'</div><div class="order-info"><b>total:</b> $'+ total + ' for ' + quantity +' items</div></div>';
    $("#updates").prepend(rr)
      .find('.order:last-child').hide();
    
    $("#updates .hidden").removeClass('hidden').fadeIn(300);
    
    
});    
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <link href='http://fonts.googleapis.com/css?family=Josefin+Slab:400,700,100' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Quicksand:300,700' rel='stylesheet' type='text/css'>
    
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>